### ISSUE TITLE
USER STORY: Account registration

### ISSUE THREAD

**Issue by Josseyo** [Josseyo/Cultivating_Intelligence#1]
As a **user** I can **register an account** so that **I can access all the features in the app**

## Acceptance Criteria

<ol>
<li> A signup button is available on the homepage.
<li> When the button is clicked, the signup page opens.
<li> When the details are filled in and submitted, a new account is created for the user.
<li> The user is notified when their account has been created.
</ol>

## Tasks

- [ ] Install allauth package
- [ ] Add allauth to requirements.txt 
- [ ] Add allauth to installed apps in settings.py
- [ ] Set up redirect urls to redirect the user to the homepage in settings.py
- [ ] Add allauth url path to urls.py
- [ ] Make migrate changes 
- [ ] Add signup link to homepage
- [ ] Customise signup form
- [ ] Add a confirmation message to let the user know that their account was created successfully
