### ISSUE TITLE
USER STORY: Type Filter

### ISSUE THREAD

**Issue by Josseyo** [Josseyo/Cultivating_Intelligence#10]
As a **user** I can ** filter the posts by type so that I can view a list of posts for the type, e.g. video, pod, text

## Acceptance Criteria:

1. A Type is set for each post and a filter is available to select a type to view the posts.

## Tasks:
Add Django filter for types.

- [ ]  Install Django filters
- [ ]  Create filters.py to include type
- [ ]  Add filter codes to PostList in views.py

**Comment by Josseyo** [comment]
In future when posts are filling up, you may want to filter posts by type such as video, pod or text.
