### ISSUE TITLE
USER STORY: Contact

### ISSUE THREAD

**Issue by Josseyo** [Josseyo/Cultivating_Intelligence#11]
As a **user** I can ** understand the purpose of the blog clearly so that I can decide whether to send a contact request.

## Acceptance Criteria:

1. To clearly explain to users why and how they should contact us
## Tasks:

- [x]  Add a Contact page explaining the purpose and how to get in contact.
- [x] Add a request collaboration form
- [x] Add confirmation message of successful submit
- [x] Add Contact page to navbar
