### ISSUE TITLE
USER STORY: Create a Post

### ISSUE THREAD

**Issue by Josseyo** [Josseyo/Cultivating_Intelligence#12]
As a **user** I can ** post my own posts** so that **I can share it with others.**

## Acceptance Criteria:

1. When the user is logged in, an Add post button is available on the homepage.
2. When the user clicks on the button, they are taken to the post form.
3. When the form is completed and submitted, the post is available for others to view on the homepage.

## Tasks:

- [ ]  Create PostForm class in forms.py to set the fields to display
- [ ]  Create Post view in views.py to display the form
- [ ]  Create post.html
- [ ]  Add the url in urls.py
