### ISSUE TITLE
USER STORY: Draft a Post

### ISSUE THREAD

**Issue by Josseyo** [Josseyo/Cultivating_Intelligence#13]
As a **user** I can **draft a post and save it so that I can return later and edit it.

## Acceptance Criteria:

1. When the user is logged in and in the add post page, they have the option to save the post as a draft.
2. The post is saved in the 'My posts' page for the user to edit it later.

## Tasks:

- [ ]  Create MyPost view in views.py to display the list of posts posted or saved by the user
- [ ]  Create my_post.html
- [ ]  Add the url to urls.py
- [ ]  Add a message to notify the user when the post is submitted
