### ISSUE TITLE
USER STORY: Edit Posts

### ISSUE THREAD

**Issue by Josseyo** [Josseyo/Cultivating_Intelligence#14]
As a **user** I can **edit my posts so that I can make changes after it has been submitted.

## Acceptance Criteria:

1. When the user is logged in, the edit button is available for each of their post
2. When the button is clicked, they are taken to the edit post form which is populated with the original details.
3. When the user makes changes and submits the changes, the post is updated on the homepage.
4. The user is notified when the updates are saved successfully.

## Tasks:

- [ ]  Create UpdateRecipe class in views.py
- [ ]  Create update_recipe.html
- [ ]  Add the url in urls.py
- [ ]  Add a message to notify the user when the post is submitted
