### ISSUE TITLE
USER STORY: Delete Posts

### ISSUE THREAD

**Issue by Josseyo** [Josseyo/Cultivating_Intelligence#15]
As a **user** I can **delete posts that I posted so that I can remove them from the site.

## Acceptance Criteria:

1. When the user is logged in, the delete button is available for each of their posts.
2. When the button is clicked, they are taken to another page to confirm the deletion.
3. When the user confirms it, the post is removed from the homepage.
4. The user is notified when the updates are saved successfully.

## Tasks:

- [ ]  Create DeletePost class in views.py
- [ ]  Create delete_post.html
- [ ]  Add the url to urls.py
- [ ]  Add the message to notify the user when the post has been deleted

Issue re-opened to replace delete_recipe.html with a modal:

- [ ] Add modal codes to post_detail.html
- [ ]  Remove delete_post.html
