### ISSUE TITLE
USER STORY: View My Posts

### ISSUE THREAD

**Issue by Josseyo** [Josseyo/Cultivating_Intelligence#16]
As a **user** I can ** view a list of posts that I have posted or drafted so that I can manage them.

## Acceptance Criteria:

1. When the user is logged in, the 'My posts' button is available.
2. When the button is clicked, the list of posted posts or drafted by the user is presented.
3. When the user selects a post from the list, the full post details open and from there, the post can be edited or deleted.

## Tasks:

- [x]  Create MyPost class in views.py
- [x]  Create my_post.html to display the posted posts by the user
- [x]  Add the url to urls.py to connect the view
- [x]  Add the url to base.html so that My Posts will be accessible from the navbar
