### ISSUE TITLE
USER STORY: Post a Comment

### ISSUE THREAD

**Issue by Josseyo** [Josseyo/Cultivating_Intelligence#18]
As a **user** I can **comment on a post so that I can share my feedback and be involved in the conversation.**

## Acceptance Criteria

1. When the user is logged in, a comment form is available for each post.
2. When the form is completed and submitted, the new comment is posted on the homepage.

## Tasks

- [x]  Install crispy-forms
- [x]  Install crispy-bootstrap5
- [x]  Add crispy-forms into settings.py
- [x]  Create CommentForm in forms.py
- [x]  Add CommentForm to views.py
- [x]  Update post_details.html to add leave a comment section
- [x]  Add a post method to PostDetail class in views.py
- [ ]  Alert the user when the comment is added
