### ISSUE TITLE
USER STORY: User Login

### ISSUE THREAD

**Issue by Josseyo** [Josseyo/Cultivating_Intelligence#2]
As a **user** I can **capability** so that **received benefit**

## Acceptance Criteria

1. Log in button is available on the homepage.
2. When the log-in button is clicked, the log-in page opens.
3. When user details are filled in correctly and submitted, the user is logged in.
4. If  user details are filled in wrongly and submitted, the user is notified and can try again

## Tasks

- [x]  Set up allauth as per Account Registration tasks first
- [x]  Customise log in form
- [x]  Create a message to let the user know that they have logged in
