### ISSUE TITLE
USER STORY: Delete a Comment

### ISSUE THREAD

**Issue by Josseyo** [Josseyo/Cultivating_Intelligence#20]
As a **user** I can **delete the comment I posted** so that **I can remove it from the comments section.**

## Acceptance Criteria:

1. When the user is logged in, the delete button is available for the comment they posted previously.
2. When the button is clicked, the user is able to delete the comment.
3. When the changes are submitted, the comment is removed from the recipe.
4. The user is notified when the comment is removed.

## Tasks:

- [ ]  Create DeleteComment class in views.py
- [ ]  Create delete_comment.html
- [ ]  Add the url to urls.py
- [ ]  Add a message to notify the user when the comment is removed
- [ ] Issue re-opened to replace delete_comment.html with a modal:

 Add modal codes to post_detail.html
 Remove delete_comment.html
