### ISSUE TITLE
USER STORY: Like a Post

### ISSUE THREAD

**Issue by Josseyo** [Josseyo/Cultivating_Intelligence#21]
As a **user** I can ** like a recipe** so that **I can interact with the content.**

## Acceptance Criteria:

1. When the user is logged in, a heart icon acts as a button.
2. The heart icon changes its colour when liked to confirm that the recipe is liked.

## Tasks:

- [x]  Create PostLike view
- [x]  Set the page to reload once the form (the button) is posted
- [x]  Update post_detail.html to include the form button
- [x]  Toggle between liked and unliked
- [x]  Add the url to urls.py in blogg-app directory
