### ISSUE TITLE
USER STORY: View a List of Liked Posts

### ISSUE THREAD

**Issue by Josseyo** [Josseyo/Cultivating_Intelligence#24]
As a **user** I can **view the list of my liked posts** so that **I can easily go back to them within the site.**

## Acceptance Criteria:

1. When the user is logged in, the 'my favourites' button is available.
2. When the button is clicked, the user is taken to a new page showing the list of their liked posts.
3. The user can easily find the details of their liked posts from My Favourites page.

## Tasks:

- [ ] Create MyPosts class in views.py
- [ ]  Create my_posts.html to display the list of posts liked by the user
- [ ]  Add the url to urls.py to connect the view
- [ ]  Add the url in base.html so that My Posts will be accessible from the navbar
