### ISSUE TITLE
USER STORY: User Logout

### ISSUE THREAD

**Issue by Josseyo** [Josseyo/Cultivating_Intelligence#3]
As a **User** I can **log out of my account ** so that **I can keep my account secure.**

## Acceptance Criteria

1. Log out button is available on the homepage when logged in.
2. When the button is clicked, the user is logged out.
3. The user is notified that they have logged out.

## Tasks

- [ ]  Set up allauth as per Account Registration tasks first
- [ ]  Customise logout form
- [ ]  Create a message to let the user know that they have logged out
