### ISSUE TITLE
VALIDATION: Frontend & Backend

### ISSUE THREAD

**Issue by Josseyo** [Josseyo/Cultivating_Intelligence#37]
## Tasks
Validate frontend and backend code:

- [x] **HTML** Validated using [W3C HTML Validator](https://validator.w3.org/)
- [x] **CSS** Validated using [Jigsaw W3 Validator](https://jigsaw.w3.org/css-validator/)
- [x] **Javascript** validated using [JS hint](https://jshint.com)
- [ ] **Python** validated using [CI Python Linter](https://pep8ci.herokuapp.com/)
- [x] **Performance** validated using [Lighthouse](https://developers.google.com/web/tools/lighthouse/)
- [ ] **Accessibility** validated using [Wave Validator](https://wave.webaim.org/)

**Comment by Josseyo** [comment]
Accessibility: contrast issues
Fix: Change colors
