### ISSUE TITLE
 USER STORY: Site Admin

### ISSUE THREAD

**Issue by Josseyo** [Josseyo/Cultivating_Intelligence#4]
As an **Admin** I can **create, update and delete posts and comments** so that **I can manage the contents of the app.**

## Acceptance Criteria:

1. The admin panel is available to the admin user/super user.
2. The admin user/super user can create, edit and delete any po and comments.

## Tasks:

- [x] Create a super user who acts as the admin
- [x] Connect the models to the admin panel
- [x] Configure display settings for the admin panel
- [x] Add filters and search bar for ease of use
