### ISSUE TITLE
USER STORY: Browse Posts

### ISSUE THREAD

**Issue by Josseyo** [Josseyo/Cultivating_Intelligence#6]
As a **User**, I can **browse a paginated  list of posts** so that **I can select one to read**

## Acceptance Criteria:

1. A paginated list of posts from the database is presented on the main page.
2. When the user selects a post, they are taken to the post's details page.

## Tasks:

- [x]  Create base.html which will be used as a base for all html templates
- [x]  Create index.html which will loop through the list of posts
- [x]  Create a class in views.py to display all posts available
- [x]  Create a paginator.html to link to index.html
- [x]  Create urls.py in blog-app directory to render BlogList as view
- [x]  Add the url to urls.py in cultivating Intelligence directory
