### ISSUE TITLE
USER STORY: View Post Details

### ISSUE THREAD

**Issue by Josseyo** [Josseyo/Cultivating_Intelligence#7]
As a **Site User**, I can **select a post from the list** so that **I can view the full content of a post

## Acceptance Criteria:

1. When the user clicks on a post, they are taken to the post details page.
2. The page contains the details;  Title, description, content, category, publish date, author

## Tasks:

- [x]  Create a class in views.py to display the details of a post selected
- [x]  Create post_detail.html to render the view
- [x]  Add the url in urls.py to connect it
