### ISSUE TITLE
USER STORY: Category Filter

### ISSUE THREAD

**Issue by Josseyo** [Josseyo/Cultivating_Intelligence#9]
As a **user** I can ** filter the posts by a post category** so that** I can view a list of posts for the post category.

## Acceptance Criteria:

1. A category is set for each post and a filter is available to select a category to view the posts

## Tasks:
Add Django ListView and create category model  for the category

- [x]  Create a Category Model
- [x]  Return the category name as a string for easy display.
- [x]  Use foreign key linking to category model to ensure posts belong to specific category
- [x]  Add a Category.html for category list view
